### ISSUE TITLE
Does not require save/publish

### ISSUE THREAD

**Issue by groundnation** [arillo-ch/silverstripe-multiselectfield#1]
Firstly, great addon! Is there a way to make any interaction with the multiselectfield prompt a user to save/publish, I can see most editors using the field, then clicking away and losing what's been done if they have not hit save or publish e.g;
![PixelSnap 2023-02-23 at 14 59 18](https://user-images.githubusercontent.com/1152620/220944033-b8ea65fc-0a55-4c87-9af7-ad44e4fc3c4c.png)

**Comment by nicolas-cusan** [comment]
Ok, you mean that there is no warning when clicking away? You are right, that would be a good addon to the UX. Will look into it soon.
