### ISSUE TITLE
JavaScript Error: Not escaped user input

### ISSUE THREAD

**Issue by rasstislav** [arillo-ch/silverstripe-multiselectfield#3]
Hello,

I have following JS error:

`Uncaught SyntaxError: Invalid regular expression: /)/: Unmatched ')' (at multiselectfield.js?m=1678283932:5:74398)`.
![image](https://user-images.githubusercontent.com/9253113/223732960-670f3ce5-4040-468e-acc4-5e01e5682ca3.png)
![image](https://user-images.githubusercontent.com/9253113/223733603-d6cf8291-d975-4a3d-b404-ca5f41c81f72.png)

User input needs to be escaped.

**Comment by nicolas-cusan** [comment]
Hi @rasstislav I the issue is now fixed. Please update and try again. Thank you for using the module.

**Comment by rasstislav** [comment]
Thanks @nicolas-cusan :-)
